### PR TITLE
Mobile command to get sync status

### PR DESCRIPTION
**Pull request by kadisonm**
Implemented a solution for #43. Users can use the command or add it to the mobile tool bar to retrieve the sync status. I also refactored getting the last sync date into misc.ts.

### CODE REVIEW

**Comment by sboesen** [comment]
Awesome! merged - will release in 0.4.35 once I briefly test it.

**Comment by sboesen** [comment]
Thanks for the code change :)

**Comment by kadisonm** [comment]
No worries, was pretty easy to implement.

**Comment by sboesen** [comment]
Released in [0.4.35](https://github.com/sboesen/remotely-sync/releases/tag/0.4.35).

Refactor is also appreciated :)

**Pull request merged**
